version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: cicd_jenkins_web:test
    container_name: fastapi-app
    volumes:
      - ./app:/app
    ports:
      - "80:80"